/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Articles } from "./Articles";
import { ArticlesCountArgs } from "./ArticlesCountArgs";
import { ArticlesFindManyArgs } from "./ArticlesFindManyArgs";
import { ArticlesFindUniqueArgs } from "./ArticlesFindUniqueArgs";
import { CreateArticlesArgs } from "./CreateArticlesArgs";
import { UpdateArticlesArgs } from "./UpdateArticlesArgs";
import { DeleteArticlesArgs } from "./DeleteArticlesArgs";
import { CommentsFindManyArgs } from "../../comments/base/CommentsFindManyArgs";
import { Comments } from "../../comments/base/Comments";
import { Authors } from "../../authors/base/Authors";
import { CreateArticleInput } from "../CreateArticleInput";
import { ArticlesService } from "../articles.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Articles)
export class ArticlesResolverBase {
  constructor(
    protected readonly service: ArticlesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Articles",
    action: "read",
    possession: "any",
  })
  async _articlesItemsMeta(
    @graphql.Args() args: ArticlesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Articles])
  @nestAccessControl.UseRoles({
    resource: "Articles",
    action: "read",
    possession: "any",
  })
  async articlesItems(
    @graphql.Args() args: ArticlesFindManyArgs
  ): Promise<Articles[]> {
    return this.service.articlesItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Articles, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Articles",
    action: "read",
    possession: "own",
  })
  async articles(
    @graphql.Args() args: ArticlesFindUniqueArgs
  ): Promise<Articles | null> {
    const result = await this.service.articles(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Articles)
  @nestAccessControl.UseRoles({
    resource: "Articles",
    action: "create",
    possession: "any",
  })
  async createArticles(
    @graphql.Args() args: CreateArticlesArgs
  ): Promise<Articles> {
    return await this.service.createArticles({
      ...args,
      data: {
        ...args.data,

        author: args.data.author
          ? {
              connect: args.data.author,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Articles)
  @nestAccessControl.UseRoles({
    resource: "Articles",
    action: "update",
    possession: "any",
  })
  async updateArticles(
    @graphql.Args() args: UpdateArticlesArgs
  ): Promise<Articles | null> {
    try {
      return await this.service.updateArticles({
        ...args,
        data: {
          ...args.data,

          author: args.data.author
            ? {
                connect: args.data.author,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Articles)
  @nestAccessControl.UseRoles({
    resource: "Articles",
    action: "delete",
    possession: "any",
  })
  async deleteArticles(
    @graphql.Args() args: DeleteArticlesArgs
  ): Promise<Articles | null> {
    try {
      return await this.service.deleteArticles(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Comments], { name: "commentsItems" })
  @nestAccessControl.UseRoles({
    resource: "Comments",
    action: "read",
    possession: "any",
  })
  async findCommentsItems(
    @graphql.Parent() parent: Articles,
    @graphql.Args() args: CommentsFindManyArgs
  ): Promise<Comments[]> {
    const results = await this.service.findCommentsItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Authors, {
    nullable: true,
    name: "author",
  })
  @nestAccessControl.UseRoles({
    resource: "Authors",
    action: "read",
    possession: "any",
  })
  async getAuthor(@graphql.Parent() parent: Articles): Promise<Authors | null> {
    const result = await this.service.getAuthor(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => String)
  async CreateArticle(
    @graphql.Args()
    args: CreateArticleInput
  ): Promise<string> {
    return this.service.CreateArticle(args);
  }
}
